select 
        ld.*,
        pup.aggregate_id as client_aggregate_id,
        pd.leadID,
        pd.activity_count,
        pd.activity_date,
        pd.activity_type,
        pd.inviting_nmlsid,
        replace(pd.inviting_lo,'  ',' ') as inviting_lo,
        pd.lo_contact_attempted,
        pd.partner,
        pd.declined,
        pd.decline_reason,
        pd.invitee_name,
        pd.total_opens,
        pd.total_clicks,
        pd.email_sent,
        pd.unique_campaign_open,
        pd.unique_campaign_click,
        pd.invite_id,
        pd.invite_email,
        pd.lofirstname,
        pd.lolastname,
        pd.agent,
        pd.purchase_specialist,
        pd.mlo_submission,
        pd.sms_invite_permission,
        pd.role,
        pd.loemail,
        pd.lastname,
        pd.firstname,
        pd.sendgrid,
        pd.shorthash,
        pd.utmsource,
        pd.disclosure,
        pd.phonenumber,
        pd.utmcampaign,
        pd.lophonenumber,
        pd.customerconnect,
        pd.confirmationrequired
         from {{ ref('leads_data_v3') }} ld 
    left outer join {{ ref('pennymac_lo_invitations_warm_transfers') }} pd on ld.id = pd.leadId
    left outer join {{ ref('partner_user_profiles') }} pup on pup.email = ld.client_email
    where ld.bank_name = 'PennyMac'