WITH registration_inv AS(
SELECT 
    partner_id,
    agent_first_name,
    agent_last_name,
    agent_name,
    pup_id AS register_id,
    has_agent,
    transaction_type AS reg_transaction_type,
    prequal AS reg_prequal,
    sfr.lofirstname AS lofirstname_reg,
    sfr.lolastname AS lolastname_reg,
    register_date,
    customer_first_name,
    customer_last_name,
    customer_full_name,
    customer_email,
    sfr.updated_at AS updated_at_reg,
    bank_partner,
    id As invitation_id,
    invite_date,
    sfi.lofirstname AS inviting_lofirstname,
    sfi.lolastname AS inviting_lolastname,
    sfi.agent AS inviting_agent,
    purchase_specialist,
    mlo_submission AS inv_mlo_submission,
    sms_invite_permission,
    role,
    loemail,
    nmlsid AS enr_nmls,
    lastname,
    sendgrid,
    firstname,
    shorthash,
    utmsource,
    disclosure,
    phonenumber,
    lophonenumber,
    mlosubmission AS reg_mlo_submission,
    customerconnect,
    currentbankcustomer,
    confirmationrequired,
    CASE 
    WHEN (firstname IS NOT NULL AND lastname IS NOT NULL) THEN 
    concat(firstname, ' ', lastname) ELSE NULL END AS invite_name,
    coalesce(email,customer_email) AS all_email
	
FROM {{ ref('stg_pmc_registrations') }} sfr
FULL OUTER JOIN {{ ref('stg_pmc_invites') }} sfi
ON sfr.customer_email = sfi.email
),
pmc_enrollments AS(
	SELECT 
        date AS enrollmentdate,
        id AS lead_id,
        client_name AS client_name_,
        client_email,
        client_phone,
        agent_name AS enroll_agent_name,
        agent_email,
        agent_phone,
        lo_name AS enrollment_lo_name,
        lo_email AS enrollment_lo_email,
        lo_phone AS enrollment_lo_phone,
        purchase_location,
        purchase_time_frame,
        prequal AS enr_prequal,
        comments,
        bank_name,
        transaction_type,
        mlo_status,
        mlo_status_time,
        rc_status,
        rc_status_time,
        agent_status,
        agent_status_time,
        closedate,
        propertyaddress,
        propertyprice,
        lenderclosedwith,
        agtcommpct,
        created AS lead_created,
        rc_accept_time_unadjusted,
        agent_assign_time_unadjusted,
        agent_assign_time,
        accept_time_delay_hrs,
        agentassign_time_delay_hrs,
        mnth_yr,
        brokerage_code,
        full_name,
        rc_name,
        rc_email,
        rc_phone,
        date_part,
        attachment,
        hb_status,
        dow,
        cst,
        cstdate,
        csthour,
        year,
        pending,
        mlosubmission AS enr_mlo_submission,
        nmlsid AS reg_nmlsid,
        outofnetworkbrokerage,
        client_first_name,
        client_last_name,
        rc_contact_first,
        rc_contact_last,
        agentfirstname,
        agentlastname,
        rc_city,
        rc_state,
        selling_address,
        bankcustomer,
        source,
        first_contact_time,
        first_contact_delay_from_enrollment,
        accept_to_contact_delay,
        major_status,
        branchname,
        branchemployee,
        coverage,
        lastpendingdate,
        inactivedate,
        timetoinactive,
        inactiverole,
        last_agent_update,
        last_rc_update,
        pendingclosedate,
        pendingpropertyaddress,
        closeaddress,
        financeclosedate,
        networkid,
        customereci,
        brokerageroutingmethod,
        agent_assigned,
        escalatedtoconcierge,
        zip,
        city,
        lo_first_name AS enrollment_lofirstname,
        lo_last_name AS enrollment_lolastname,
        hb_status_time,
        homesaleprice,
        updated_at AS enr_updated_at,
        avg_price,
        price_range_lower_bound,
        price_range_upper_bound    
    FROM {{ ref('leads_data_v3') }}
	WHERE bank_name = 'PennyMac'
),
combine AS(
	SELECT * FROM registration_inv
	FULL OUTER JOIN pmc_enrollments
	ON lower(pmc_enrollments.client_email) = lower(registration_inv.all_email)
),
final AS(
	SELECT 
	coalesce(enroll_agent_name, agent_name) AS agentname_total,
	coalesce(all_email, client_email) AS client_email_total,
	coalesce(enrollment_lo_name, CONCAT(lofirstname_reg,' ',lolastname_reg),CONCAT(inviting_lofirstname,' ',inviting_lolastname)) AS loname_total,
    coalesce(transaction_type, reg_transaction_type) AS transaction_type_total,
    coalesce(enr_nmls ,reg_nmlsid) AS nmlsid_total,
    coalesce(enr_mlo_submission, reg_mlo_submission, inv_mlo_submission) AS mlo_submission,
    coalesce(invite_name, client_name_) AS client_name,
	*
	FROM
	combine
)
SELECT * FROM final

