SNS_TOPIC_ARN_VARIABLE_NAME_ON_AIRFLOW = 'SNS_TOPIC_ARN_VARIABLE_NAME_ON_AIRFLOW'

CUSTOM_AIRFLOW_CONSTANTS = {
    SNS_TOPIC_ARN_VARIABLE_NAME_ON_AIRFLOW: 'sns_task_failure_alert_topic_arn'
}

LOCAL_GX_PROJECT_PATH = '/tmp/great_expectations_project'
LOCAL_GX_TMP_PATH = '/tmp/'
