#!/bin/bash

AIRFLOW_VERSION=2_4
DOCKER_COMPOSE_PROJECT_NAME=aws-mwaa-local-runner-$AIRFLOW_VERSION
LOCAL_ENV_FILE_PATH="dev.env"
export AIRFLOW_LOCAL_PORT=8080
if test -f "$LOCAL_ENV_FILE_PATH"; then
  export $(xargs < $LOCAL_ENV_FILE_PATH)
fi

export AWS_CREDS_FOLDER_PATH="${AWS_CREDS_FOLDER_PATH:-${SOURCE_CODE_ROOT}/scripts/aws_mwaa_local_runner/docker/config/aws_creds_default}"

cd "$SOURCE_CODE_ROOT" || exit
python "$SOURCE_CODE_ROOT"/scripts/airflow_build --local-dag-dir ${LOCAL_DAG_DIR_PATH} --update-dynamic-dags --dags-directory "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_DAGS_PATH" --update-common-dags --update-standalone-dags --projects "$AIRFLOW_PROJECT" --requirements-file "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_REQUIREMENTS_PATH" --plugins-directory "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_PLUGINS_PATH" --test
cd "$SOURCE_CODE_ROOT/scripts/aws_mwaa_local_runner" || exit
export LOCAL_DBT_PROJECT_DIR="${SOURCE_CODE_ROOT}/${LOCAL_DBT_PROJECT_DIR}"
export LOCAL_GREAT_EXPECTATIONS_PROJECT_DIR="${SOURCE_CODE_ROOT}/${LOCAL_GREAT_EXPECTATIONS_PROJECT_DIR}"
export SOURCE_CODE_ROOT=''
export LOCAL_AIRFLOW_REQUIREMENTS_PATH='/tmp/airflow_requirements.txt'
export LOCAL_AIRFLOW_PLUGINS_PATH='/tmp/airflow_dags_plugins'
export LOCAL_AIRFLOW_DAGS_PATH="${LOCAL_DAG_DIR_PATH:-None}"
unzip -o "$LOCAL_AIRFLOW_PLUGINS_PATH.zip" -d "$LOCAL_AIRFLOW_PLUGINS_PATH"

display_help() {
   # Display Help
   echo "======================================"
   echo "   MWAA Local Runner CLI"
   echo "======================================"
   echo "Syntax: mwaa-local-runner [command]"
   echo "Airflow version $AIRFLOW_VERSION"
   echo "---commands---"
   echo "help                   Print CLI help"
   echo "build-image            Build Image Locally"
   echo "reset-db               Reset local PostgresDB container."
   echo "start                  Start Airflow local environment. (LocalExecutor, Using postgres DB)"
   echo "stop                   Stop Airflow local environment. (LocalExecutor, Using postgres DB)"
   echo "test-requirements      Install requirements on an ephemeral instance of the container."
   echo "package-requirements   Download requirements WHL files into plugins folder."
   echo "validate-prereqs       Validate pre-reqs installed (docker, docker-compose, python3, pip3)"
   echo
}

validate_prereqs() {
   docker -v >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      echo -e "'docker' is not installed or not runnable without sudo. \xE2\x9D\x8C"
   else
      echo -e "Docker is Installed. \xE2\x9C\x94"
   fi

   docker-compose -v >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      echo -e "'docker-compose' is not installed. \xE2\x9D\x8C"
   else
      echo -e "Docker compose is Installed. \xE2\x9C\x94"
   fi

   python3 --version >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      echo -e "Python3 is not installed. \xE2\x9D\x8C"
   else
      echo -e "Python3 is Installed \xE2\x9C\x94"
   fi

   pip3 --version >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      echo -e "Pip3 is not installed. \xE2\x9D\x8C"
   else
      echo -e "Pip3 is Installed. \xE2\x9C\x94"
   fi
}

build_image() {
   docker build --rm --compress -t amazon/mwaa-local:$AIRFLOW_VERSION ./docker
}

case "$1" in
validate-prereqs)
   validate_prereqs
   ;;
test-requirements)
   BUILT_IMAGE=$(docker images -q amazon/mwaa-local:$AIRFLOW_VERSION)
   if [[ -n "$BUILT_IMAGE" ]]; then
     echo "Container amazon/mwaa-local:$AIRFLOW_VERSION exists. Skipping build"
   else
     echo "Container amazon/mwaa-local:$AIRFLOW_VERSION not built. Building locally."
     build_image
   fi
   docker run -v "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_DAGS_PATH":/usr/local/airflow/dags -v "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_PLUGINS_PATH":/usr/local/airflow/plugins -v "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_REQUIREMENTS_PATH":/usr/local/airflow/requirements/requirements.txt -it amazon/mwaa-local:$AIRFLOW_VERSION test-requirements
   ;;
package-requirements)
   BUILT_IMAGE=$(docker images -q amazon/mwaa-local:$AIRFLOW_VERSION)
   if [[ -n "$BUILT_IMAGE" ]]; then
     echo "Container amazon/mwaa-local:$AIRFLOW_VERSION exists. Skipping build"
   else
     echo "Container amazon/mwaa-local:$AIRFLOW_VERSION not built. Building locally."
     build_image
   fi
   docker run -v "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_DAGS_PATH":/usr/local/airflow/dags -v "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_PLUGINS_PATH":/usr/local/airflow/plugins -v "$SOURCE_CODE_ROOT/$LOCAL_AIRFLOW_REQUIREMENTS_PATH":/usr/local/airflow/requirements/requirements.txt -it amazon/mwaa-local:$AIRFLOW_VERSION package-requirements
   ;;   
build-image)
   build_image
   ;;
reset-db)
   docker-compose -p $DOCKER_COMPOSE_PROJECT_NAME -f ./docker/docker-compose-resetdb.yml up --abort-on-container-exit
   ;;
start)
   docker-compose -p $DOCKER_COMPOSE_PROJECT_NAME -f ./docker/docker-compose-local.yml up
   ;;
stop)
   docker-compose -p $DOCKER_COMPOSE_PROJECT_NAME -f ./docker/docker-compose-local.yml down
   ;;
help)
   display_help
   ;;
*)
   echo "No command specified, displaying help"
   display_help
   ;;
esac
