
/* GA4 data starting at 2023-08-01 */
with union_cte AS(
select
	account_created,
	am_i_purchase_ready_profile_builder,
	formatted_date,
	homestory_lead_submitted,
	homestory_lead_submitted_about_landing_page,
	homestory_lead_submitted_home_page,
	homestory_lead_submitted_lo,
	null as homestory_lead_submitted_new_self_enrollment,
	null as homestory_lead_submitted_pdp,
	homestory_lead_submitted_search_landing_page,
	lead_submitted_pdp,
	logged_in,
	property_saved,
	search_saved,
	sessioncampaignname,
	sourcemedium,
	teambuilder_completion,
	viewed_detail_page,
	viewed_details_page,
	viewed_pdp,
	viewed_search_results,
	'citizens' as partner
from {{ ref('ga4_citizens_goals') }} 
union all 
select
	account_created,
	am_i_purchase_ready_profile_builder,
	formatted_date,
	homestory_lead_submitted,
	homestory_lead_submitted_about_landing_page,
	null as homestory_lead_submitted_home_page,
	homestory_lead_submitted_lo,
	null as homestory_lead_submitted_new_self_enrollment,
	null as homestory_lead_submitted_pdp,
	homestory_lead_submitted_search_landing_page,
	lead_submitted_pdp,
	logged_in,
	property_saved,
	search_saved,
	sessioncampaignname,
	sourcemedium,
	teambuilder_completion,
	viewed_detail_page,
	viewed_details_page,
	viewed_pdp,
	viewed_search_results,
	'sofi' as partner
from {{ ref('ga4_sofi_goals') }} 
union all 
select
	account_created,
	null as am_i_purchase_ready_profile_builder,
	formatted_date,
	homestory_lead_submitted,
	null as homestory_lead_submitted_about_landing_page,
	null as homestory_lead_submitted_home_page,
	null as homestory_lead_submitted_lo,
	cast(homestory_lead_submitted_new_self_enrollment as text),
	cast(homestory_lead_submitted_pdp as text),
	null as homestory_lead_submitted_search_landing_page,
	null as lead_submitted_pdp,
	logged_in,
	property_saved,
	search_saved,
	sessioncampaignname,
	sourcemedium,
	null as teambuilder_completion,
	null as viewed_detail_page,
	viewed_details_page,
	null as viewed_pdp,
	viewed_search_results,
	'lakeview' as partner
from {{ ref('ga4_lakeview_goals') }} 
union all
select
	account_created,
	null as am_i_purchase_ready_profile_builder,
	formatted_date,
	homestory_lead_submitted,
	homestory_lead_submitted_about_landing_page,
	null as homestory_lead_submitted_home_page,
	homestory_lead_submitted_lo,
	null as homestory_lead_submitted_new_self_enrollment,
	cast(homestory_lead_submitted_pdp as text),
	homestory_lead_submitted_search_landing_page,
	null as lead_submitted_pdp,
	logged_in,
	property_saved,
	search_saved,
	sessioncampaignname,
	sourcemedium,
	null as teambuilder_completion,
	viewed_detail_page,
	viewed_details_page,
	null as viewed_pdp,
	viewed_search_results,
	'pennymac' as partner
from {{ ref('ga4_pmc_goals') }} 
union all
select
	account_created,
	null as am_i_purchase_ready_profile_builder,
	formatted_date,
	homestory_lead_submitted,
	null as homestory_lead_submitted_about_landing_page,
	null as homestory_lead_submitted_home_page,
	null as homestory_lead_submitted_lo,
	null as homestory_lead_submitted_new_self_enrollment,
	cast(homestory_lead_submitted_pdp as text),
	null as homestory_lead_submitted_search_landing_page,
	null as lead_submitted_pdp,
	logged_in,
	property_saved,
	search_saved,
	sessioncampaignname,
	sourcemedium,
	null as teambuilder_completion,
	null as viewed_detail_page,
	viewed_details_page,
	null as viewed_pdp,
	viewed_search_results,
	'fidelity' as partner
from {{ ref('stg_ga4_fidelity_goals') }} 
union all
select
	account_created,
	null as am_i_purchase_ready_profile_builder,
	formatted_date,
	homestory_lead_submitted,
	null as homestory_lead_submitted_about_landing_page,
	null as homestory_lead_submitted_home_page,
	null as homestory_lead_submitted_lo,
	null as homestory_lead_submitted_new_self_enrollment,
	cast(homestory_lead_submitted_pdp as text),
	null as homestory_lead_submitted_search_landing_page,
	null as lead_submitted_pdp,
	null as logged_in,
	property_saved,
	null as search_saved,
	sessioncampaignname,
	sourcemedium,
	null as teambuilder_completion,
	null as viewed_detail_page,
	viewed_details_page,
	null as viewed_pdp,
	viewed_search_results,
	'freedom' as partner
from {{ ref('stg_ga4_freedom_goals') }}
),
normalize_cte AS(
	select 
		account_created,
		am_i_purchase_ready_profile_builder,
		formatted_date as ga_date,
		homestory_lead_submitted,
		homestory_lead_submitted_about_landing_page,
		homestory_lead_submitted_home_page,
		homestory_lead_submitted_lo,
		homestory_lead_submitted_new_self_enrollment::double precision as homestory_lead_submitted_new_self_enrollment,
		homestory_lead_submitted_pdp::double precision as homestory_lead_submitted_pdp,
		homestory_lead_submitted_search_landing_page,
		lead_submitted_pdp,
		logged_in,
		property_saved,
		search_saved,
		sessioncampaignname,
		sourcemedium,
		teambuilder_completion,
		viewed_detail_page,
		viewed_details_page,
		viewed_pdp,
		viewed_search_results,
		partner
from union_cte
	)
select * from normalize_cte
where ga_date >= '2023-06-27'