with union_cte AS(
select
	account_created,
	cast(null as bigint) as am_i_purchase_ready_profile_builder,
	ga_date,
	homestory_lead_submitted,
	cast(null as bigint) as homestory_lead_submitted_about_landing_page,
	cast(null as bigint) as homestory_lead_submitted_home_page,
	cast(null as bigint) as homestory_lead_submitted_lo,
	cast(null as bigint) as homestory_lead_submitted_new_self_enrollment,
	homestory_lead_submitted_pdp,
	cast(null as bigint) as homestory_lead_submitted_search_landing_page,
	cast(null as bigint) as lead_submitted_pdp,
	cast(null as bigint) as logged_in,
	property_saved,
	cast(null as bigint) as search_saved,
	null as sessioncampaignname,
	null as sourcemedium,
	cast(null as bigint) as teambuilder_completion,
	cast(null as bigint) as viewed_detail_page,
	viewed_details_page,
	cast(null as bigint) as viewed_pdp,
	viewed_search_results,
	'citizens' as partner
from {{ ref('stg_citizens_goals') }}
union all 
select
	account_created,
	am_i_purchase_ready_profile_builder,
	ga_date,
	homestory_lead_submitted,
	cast(null as bigint) as homestory_lead_submitted_about_landing_page,
	cast(null as bigint) as homestory_lead_submitted_home_page,
	cast(null as bigint) as homestory_lead_submitted_lo,
	cast(null as bigint) as homestory_lead_submitted_new_self_enrollment,
	cast(null as bigint) as homestory_lead_submitted_pdp,
	lead_submitted_search_landing_page as homestory_lead_submitted_search_landing_page,
	lead_submitted_pdp,
	cast(null as bigint) as logged_in,
	property_saved,
	search_saved,
	null as sessioncampaignname,
	null as sourcemedium,
	teambuilder_completion,
	cast(null as bigint) as viewed_detail_page,
	cast(null as bigint) as viewed_details_page,
	viewed_pdp,
	viewed_search_results,
	'sofi' as partner
from {{ ref('stg_sofi_goals') }}
union all 
select
	account_created,
	cast(null as bigint) as am_i_purchase_ready_profile_builder,
	ga_date,
	homestory_lead_submitted,
	cast(null as bigint) as homestory_lead_submitted_about_landing_page,
	cast(null as bigint) as homestory_lead_submitted_home_page,
	cast(null as bigint) as homestory_lead_submitted_lo,
	cast(null as bigint) as homestory_lead_submitted_new_self_enrollment,
	homestory_lead_submitted_pdp,
	cast(null as bigint) as homestory_lead_submitted_search_landing_page,
	cast(null as bigint) as lead_submitted_pdp,
	logged_in,
	property_saved,
	search_saved,
	null as sessioncampaignname,
	ga_sourceMedium as sourcemedium,
	cast(null as bigint) as teambuilder_completion,
	cast(null as bigint) as viewed_detail_page,
	viewed_details_page,
	cast(null as bigint) as viewed_pdp,
	viewed_search_results,
	'lakeview' as partner
from {{ ref('stg_lakeview_goals') }}
union all
select
	account_created,
	cast(null as bigint) as am_i_purchase_ready_profile_builder,
	ga_date,
	homestory_lead_submitted,
	homestory_lead_submitted_about_landing_page,
	cast(null as bigint) as homestory_lead_submitted_home_page,
	homestory_lead_submitted_lo,
	cast(null as bigint) as homestory_lead_submitted_new_self_enrollment,
	homestory_lead_submitted_pdp,
	homestory_lead_submitted_search_landing_page,
	cast(null as bigint) as lead_submitted_pdp,
	cast(null as bigint) as logged_in,
	property_saved,
	search_saved,
	null as sessioncampaignname,
	null as sourcemedium,
	cast(null as bigint) as teambuilder_completion,
	viewed_detail_page,
	cast(null as bigint) as viewed_details_page,
	cast(null as bigint) as viewed_pdp,
	viewed_search_results,
	'pennymac' as partner
from {{ ref('stg_pmc_goals') }}
union all
select
	account_created,
	cast(null as bigint) as am_i_purchase_ready_profile_builder,
	ga_date,
	homestory_lead_submitted,
	cast(null as bigint) as homestory_lead_submitted_about_landing_page,
	cast(null as bigint) as homestory_lead_submitted_home_page,
	cast(null as bigint) as homestory_lead_submitted_lo,
	cast(null as bigint) as homestory_lead_submitted_new_self_enrollment,
	homestory_lead_submitted_pdp,
	cast(null as bigint) as homestory_lead_submitted_search_landing_page,
	cast(null as bigint) as lead_submitted_pdp,
	cast(null as bigint) as logged_in,
	property_saved,
	cast(null as bigint) as search_saved,
	null as sessioncampaignname,
	null as sourcemedium,
	cast(null as bigint) as teambuilder_completion,
	cast(null as bigint) as  viewed_detail_page,
	viewed_details_page,
	cast(null as bigint) as viewed_pdp,
	viewed_search_results,
	'fidelity' as partner
from {{ ref('stg_fidelity_goals') }}
union all
select
	account_created,
	cast(null as bigint) as am_i_purchase_ready_profile_builder,
	ga_date,
	homestory_lead_submitted,
	cast(null as bigint) as homestory_lead_submitted_about_landing_page,
	cast(null as bigint) as homestory_lead_submitted_home_page,
	cast(null as bigint) as homestory_lead_submitted_lo,
	cast(null as bigint) as homestory_lead_submitted_new_self_enrollment,
	homestory_lead_submitted_pdp,
	cast(null as bigint) as homestory_lead_submitted_search_landing_page,
	cast(null as bigint) as lead_submitted_pdp,
	cast(null as bigint) as logged_in,
	property_saved,
	cast(null as bigint) as search_saved,
	null as sessioncampaignname,
	null as sourcemedium,
	cast(null as bigint) as teambuilder_completion,
	cast(null as bigint) as  viewed_detail_page,
	viewed_details_page,
	cast(null as bigint) as viewed_pdp,
	viewed_search_results,
	'freedom' as partner
from {{ ref('stg_freedom_goals') }}
),
normalize_cte AS(
	select 
		account_created,
		am_i_purchase_ready_profile_builder,
		ga_date,
		homestory_lead_submitted,
		homestory_lead_submitted_about_landing_page,
		homestory_lead_submitted_home_page,
		homestory_lead_submitted_lo,
		homestory_lead_submitted_new_self_enrollment::double precision as homestory_lead_submitted_new_self_enrollment,
		homestory_lead_submitted_pdp::double precision as homestory_lead_submitted_pdp,
		homestory_lead_submitted_search_landing_page,
		lead_submitted_pdp,
		logged_in,
		property_saved,
		search_saved,
		sessioncampaignname,
		sourcemedium,
		teambuilder_completion,
		viewed_detail_page,
		viewed_details_page,
		viewed_pdp,
		viewed_search_results,
		partner
from union_cte
	)
select * from normalize_cte
where ga_date < '2023-06-27'
order by ga_date desc 