version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"
    docker-proxy:
        image: bobrik/socat
        command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
        ports:
            - "2376:2375"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    local-runner:
        image: amazon/mwaa-local:2_4
        platform: "linux/amd64"
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${SOURCE_CODE_ROOT}/${LOCAL_AIRFLOW_DAGS_PATH}:/usr/local/airflow/dags"
            - "${SOURCE_CODE_ROOT}/${LOCAL_AIRFLOW_PLUGINS_PATH}:/usr/local/airflow/plugins"
            - "${SOURCE_CODE_ROOT}/${LOCAL_AIRFLOW_REQUIREMENTS_PATH}:/usr/local/airflow/requirements/requirements.txt"
            - "${AWS_CREDS_FOLDER_PATH}:/usr/local/airflow/.aws"
            - "${SOURCE_CODE_ROOT}/${LOCAL_DBT_PROJECT_DIR}:/usr/local/dbt"
            - "${SOURCE_CODE_ROOT}/${LOCAL_GREAT_EXPECTATIONS_PROJECT_DIR}:/tmp/great_expectations"
        ports:
            - "${AIRFLOW_LOCAL_PORT}:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
            - ./config/.env.localrunner