{{
  config(
	materialized = 'table',
	tags=['bitly'],
  enabled=true
	)
}}
select
	agent_email,
	agent_name,
	NULL AS agent_phone,
	agentacceptcount,
	(agentaccepttime - interval '5 Hours') as agentaccepttime,
	agentaggregateid,
	agentassigned,
	agentcreatedcount,
	agentdirecttimeoutcount,
	agentfirstname,
	agentlastname,
	agentmobilephone,
	agentnetworkname,
	agentofficephone,
	agentselecttimeoutcount,
	agentstatus,
	agentstatustime,
	agenttimeoutcount,
	assignedagenttotalreferrals,
	attached,
	brokerage,
	brokerage_code,
	brokerageemail,
	brokeragegroup,
	brokeragephone,
	businesshours,
	NULL AS caelegacyagent,
	chase_id,
	claimdate,
	client_email,
	client_first_name,
	client_last_name,
	client_name,
	client_phone,
	closeaddress,
	closedate,
	closeprice,
	comments,
	NULL AS commissionpct,
	conciergestatus,
	conciergestatustime,
	confirmedcustomerconnection,
	consumer_confirmed,
	created,
	cst,
	cstdate,
	csthour,
	customereci,
	NULL customerfthb,
	customerlanguage,
	customrouting,
	date,
	date_part,
	divisionmanager,
	divisionname,
	dow,
	enroll_mnth_yr,
	enrolleddate,
	enrollmenttype,
	escalatedtoconcierge,
	financeclosedate,
	financingstatus,
	financingstatustime,
	first_agent_contact_time,
	first_contact_time,
	firstaccepteddate,
	firstassigntime,
	firstconfirmeddate,
	firstrewardsteamcontact,
	firstrouteddate,
	full_name,
	hb_status,
	hla_first_name,
	hla_last_name,
	hlaaggregateid,
	hlacheck,
	hlaentered,
	hlasid,
	hsaaggregateid,
	hsafullname,
	id,
	invite_mnth_yr,
	inviteddate,
	lastcontactdate,
	lastpendingdate,
	leadassignmentcount,
	cast(leaduuid as text) as leaduuid,
	cast(lead_aggregateid as text) as lead_aggregateid, 
	lenderclosedwith,
	lmagregateid,
	lmemail,
	lmfullname,
	lo_email,
	lo_name,
	NULL AS lo_phone,
	loan_details_sharing_enabled,
	loenrollmentform,
	lowcoverage,
	majorstatus,
	sms.medium,
	networkid,
	NULL AS nmlsid,
	normalizedcity,
	normalizedstate,
	normalizedzip,
	offereddate,
	originalroutingtype,
	pending,
	pendingclosedate,
	pendingpropertyaddress,
	prequal,
	price_range_lower_bound,
	price_range_upper_bound,
	purchase_location,
	purchase_time_frame,
	NULL AS rc_city,
	rc_email,
	rc_name,
	rc_phone,
	NULL AS rc_state,
	rcassigned,
	rcdirect,
	realestatestatus,
	realestatestatustime,
	reassignmentcount,
	referral_fee_transaction,
	referralemail,
	rejectedcount,
	rewardsteam,
	rewardsteamconfirmed,
	rewardsteamcontacted,
	routingattempts,
	routingtype,
	selling_address,
	slmaggregateid,
	slmemail,
	slmfullname,
	cet.smsdate,
	cet.smspermission,
	source,
	sponsordivision,
	sponsorhla,
	sponsorlm,
	sponsorslm,
	stringzip,
	timetoaccepthours,
	timetoagentcontacthrs,
	timetofirstcontacthrs,
	timetoselecthrs,
	total_assignments,
	totalinvitesbylo,
	transaction_type,
	unacceptedreferral,
	unadjustedenrolldate,
	unadjustedfirstroutedate,
	unadjustedinvitedate,
	verificationstatus,
	waitingtimehours,
	weeknum,
	year,
	zerocoverage
from
	{{ ref('chase_enrollments_test') }}  cet 
left outer join (SELECT lead_id, created as smsdate,
                data->'trafficSource'->>'medium' AS medium,
                data->>'smsInvitePermission' AS smspermission
                FROM {{ ref('leads_data') }} 
                where data->>'smsInvitePermission' = 'true' ) sms on sms.lead_id=cet.id
