{{
  config(
    materialized = 'table',
    )
}}

with 
profiles_cte AS (
    select
    pup.aggregate_id,
    concat(pup.first_name,' ',pup.last_name) as agent_name,
    pup.brokerage_code,
    pup.email as agent_email,
    pup.verification_status as internal_verification_status,
    case when pup.verification_status = 'Verified-Provisional' then 'Verified-Verified'
    when pup.verification_status = 'Verified-Select Only' then 'Verified-Verified'
    else pup.verification_status end as verification_status
    from {{ ref("partner_user_profiles") }} pup
),
enrollments as (
    select
        id,
        client_name,
        client_first_name,
        client_last_name,
        client_contact_methods,
        agent_email,
        agent_name,
        agent_phone,
        agentaccepttime,
        agentaggregateid,
        agentassigned,
        agentfirstname,
        agentlastname,
        agentmobilephone,
        agentnetworkname,
        agentofficephone,
        agentstatus,
        agentstatustime,
        brokerage,
        brokerage_code,
        brokerageemail,
        brokeragegroup,
        brokeragephone,
        businesshours,
        caelegacyagent,
        campaign,
        chase_id,
        claimdate,
        closeaddress,
        closedate,
        closeprice,
        comments,
        commissionpct,
        conciergestatus,
        conciergestatustime,
        created,
        cst,
        cstdate,
        csthour,
        customereci,
        customerfthb,
        customerlanguage,
        customrouting,
        date,
        date_part,
        divisionmanager,
        divisionname,
        enroll_mnth_yr,
        enrolleddate,
        enrollmenttype,
        financeclosedate,
        financingstatus,
        financingstatustime,
        first_agent_contact_time,
        first_contact_time,
        firstaccepteddate,
        firstassigntime,
        firstconfirmeddate,
        firstrewardsteamcontact,
        full_name,
        firstrouteddate,
        hb_status,
        hla_first_name,
        hla_last_name,
        hlaaggregateid,
        hlacheck,
        hlaentered,
        hlasid,
        hsaaggregateid,
        hsafullname,
        inactivedate,
        invite_mnth_yr,
        inviteddate,
        invitemedium,
        last_agent_update,
        lastcontactdate,
        lastpendingdate,
        leaduuid,
        lenderclosedwith,
        lmagregateid,
        lmemail,
        lmfullname,
        lo_email,
        lo_name,
        lo_phone,
        loenrollmentform,
        majorstatus,
        networkid,
        nmlsid,
        normalizedcity,
        normalizedclosedate,
        normalizedstate,
        normalizedzip,
        offereddate,
        originalroutingtype,
        pending,
        pendingclosedate,
        pendingpropertyaddress,
        purchase_location,
        rc_city,
        rc_email,
        rc_name,
        rc_phone,
        rc_state,
        rcassigned,
        rcdirect,
        realestatestatus,
        realestatestatustime,
        referralemail,
        rewardsteam,
        routingtype,
        selling_address,
        slmaggregateid,
        slmemail,
        slmfullname,
        smsdate,
        smspermission,
        smssource,
        source,
        sponsordivision,
        sponsorhla,
        sponsorlm,
        sponsorslm,
        stringzip,
        timetoaccepthours,
        timetoagentcontacthrs,
        timetofirstcontacthrs,
        timetoselecthrs,
        transaction_type,
        unacceptedreferral,
        unadjustedenrolldate,
        unadjustedfirstroutedate,
        unadjustedinvitedate,
        verificationstatus,
        internal_verificationstatus,
        weeknum,
        year,
        agentacceptcount,
        agentcreatedcount,
        agentdirecttimeoutcount,
        agentselecttimeoutcount,
        agenttimeoutcount,
        assignedagenttotalreferrals,
        attached,
        confirmedcustomerconnection,
        consumer_confirmed,
        dow,
        escalatedtoconcierge,
        leadassignmentcount,
        loan_details_sharing_enabled,
        lowcoverage,
        prequal,
        price_range_lower_bound,
        price_range_upper_bound,
        purchase_time_frame,
        reassignmentcount,
        referral_fee_transaction,
        rejectedcount,
        rewardsteamconfirmed,
        rewardsteamcontacted,
        routingattempts,
        total_assignments,
        totalinvitesbylo,
        waitingtimehours,
        zerocoverage
from {{ ref("chase_enrollments_test") }} cet
)
,
{#- 
cte AS (
    SELECT
        LEAD_ID,
        agent_ids
    FROM {{ ref('stg_routing_events') }}
    where agent_ids is not null

)
,
 -#}

routing_cte AS (
select
	a.lead_id,
--ca.profile_aggregate_id,
a.smName,
a.event_type,
a.action_agent,
a.routing_method,
a.invite_token,
a.timestamp,
a.routing_start_time,
a.routing_initiated_time,
a.agent_limit,
a.parent_profile_id,
--lrp.not_parent_profile_id,
a.parent_division,
cast(a.hla_selected_agent1 as uuid) as hla_selected_agent1,
cast(a.hla_selected_agent2 as uuid) as hla_selected_agent2,
cast(a.hla_selected_agent3 as uuid) as hla_selected_agent3,
case when a.hla_selected_agent1 is not null then 'True' else 'False' end as advanced_agent_select_flag,
a.hla_selected_agent_count,
--lrp.data_field,
a.agent_count,
a.agent1,
a.agent2,
a.agent3,
a.agent4,
a.agent5,
a.agent6,
a.agent7,
a.agent8,
a.agent9,
a.agent10,
ce.*
from {{ ref('stg_routing_events') }} a
--left join lead_rank_params_cte lrp on lrp.lead_id = a.lead_id
--left join currently_assigned_agent_cte ca on ca.lead_id = a.lead_id
--left join profiles_cte pc on pc.aggregate_id = cast(_airbyte_data->'agents'->0->>'aggregateId' as uuid)
--left outer join profiles_cte pcc on pcc.aggregate_id = ca.profile_aggregate_id
left join enrollments ce on ce.id = a.lead_id
)
select 
    rc.*,
    coalesce(pup1.agent_name,ld.ld_hla_selected_agent1_name) as hla_selected_agent1_name,
    coalesce(pup1.brokerage_code,ld.ld_hla_selected_agent1_brokerage_code) as hla_selected_agent1_brokerage_code,
    coalesce(pup1.agent_email,ld.ld_hla_selected_agent1_email) as hla_selected_agent1_email,
    pup1.internal_verification_status as hla_selected_agent_1_verification_status,
    hla1.hlaagregateid as hla_selected_agent1_hla,
    case when hla1.hlaagregateid is null then 'False' else 'True' end as hla_selected_agent_1_affiliated,
    coalesce(pup2.agent_name,ld.ld_hla_selected_agent2_name) as hla_selected_agent2_name,
    coalesce(pup2.brokerage_code,ld.ld_hla_selected_agent2_brokerage_code) as hla_selected_agent2_brokerage_code,
    coalesce(pup2.agent_email,ld.ld_hla_selected_agent2_email) as hla_selected_agent2_email,
    pup2.internal_verification_status as hla_selected_agent_2_verification_status,
    hla2.hlaagregateid as hla_selected_agent2_hla,
    case when hla2.hlaagregateid is null then 'False' else 'True' end as hla_selected_agent_2_affiliated,
    coalesce(pup3.agent_name,ld.ld_hla_selected_agent3_name) as hla_selected_agent3_name,
    coalesce(pup3.brokerage_code,ld.ld_hla_selected_agent3_brokerage_code) as hla_selected_agent3_brokerage_code,
    coalesce(pup3.agent_email,ld.ld_hla_selected_agent3_email) as hla_selected_agent3_email,
    pup3.internal_verification_status as hla_selected_agent_3_verification_status,
    hla3.hlaagregateid as hla_selected_agent3_hla,
    case when hla3.hlaagregateid is null then 'False' else 'True' end as hla_selected_agent_3_affiliated,
    pup4.agent_name as agent1_name,
    pup4.brokerage_code as agent1_brokerage_code,
    pup4.agent_email as agent1_email,
    pup4.internal_verification_status as agent1_verification_status,
    hla4.hlaagregateid as agent1_hla,
    case when hla4.hlaagregateid is null then 'False' else 'True' end as agent_1_affiliated,
    pup5.agent_name as agent2_name,
    pup5.brokerage_code as agent2_brokerage_code,
    pup5.agent_email as agent2_email,
    pup5.internal_verification_status as agent2_verification_status,
    hla5.hlaagregateid as agent2_hla,
    case when hla5.hlaagregateid is null then 'False' else 'True' end as agent_2_affiliated,
    pup6.agent_name as agent3_name,
    pup6.brokerage_code as agent3_brokerage_code,
    pup6.agent_email as agent3_email,
    pup6.internal_verification_status as agent3_verification_status,
    hla6.hlaagregateid as agent3_hla,
    case when hla6.hlaagregateid is null then 'False' else 'True' end as agent_3_affiliated,
    pup7.agent_name as agent4_name,
    pup7.brokerage_code as agent4_brokerage_code,
    pup7.agent_email as agent4_email,
    pup7.internal_verification_status as agent4_verification_status,
    hla7.hlaagregateid as agent4_hla,
    case when hla7.hlaagregateid is null then 'False' else 'True' end as agent_4_affiliated,
    pup8.agent_name as agent5_name,
    pup8.brokerage_code as agent5_brokerage_code,
    pup8.agent_email as agent5_email,
    pup8.internal_verification_status as agent5_verification_status,
    hla8.hlaagregateid as agent5_hla,
    case when hla8.hlaagregateid is null then 'False' else 'True' end as agent_5_affiliated,
    pup9.agent_name as agent6_name,
    pup9.brokerage_code as agent6_brokerage_code,
    pup9.agent_email as agent6_email,
    pup9.internal_verification_status as agent6_verification_status,
    hla9.hlaagregateid as agent6_hla,
    case when hla9.hlaagregateid is null then 'False' else 'True' end as agent_6_affiliated,
    pup10.agent_name as agent7_name,
    pup10.brokerage_code as agent7_brokerage_code,
    pup10.agent_email as agent7_email,
    pup10.internal_verification_status as agent7_verification_status,
    hla10.hlaagregateid as agent7_hla,
    case when hla10.hlaagregateid is null then 'False' else 'True' end as agent_7_affiliated,
    pup11.agent_name as agent8_name,
    pup11.brokerage_code as agent8_brokerage_code,
    pup11.agent_email as agent8_email,
    pup11.internal_verification_status as agent8_verification_status,
    hla11.hlaagregateid as agent8_hla,
    case when hla11.hlaagregateid is null then 'False' else 'True' end as agent_8_affiliated,
    pup12.agent_name as agent9_name,
    pup12.brokerage_code as agent9_brokerage_code,
    pup12.agent_email as agent9_email,
    pup12.internal_verification_status as agent9_verification_status,
    hla12.hlaagregateid as agent9_hla,
    case when hla12.hlaagregateid is null then 'False' else 'True' end as agent_9_affiliated,
    pup13.agent_name as agent10_name,
    pup13.brokerage_code as agent10_brokerage_code,
    pup13.agent_email as agent10_email,
    pup13.internal_verification_status as agent10_verification_status,
    hla13.hlaagregateid as agent10_hla,
    case when hla13.hlaagregateid is null then 'False' else 'True' end as agent_10_affiliated,
    pup14.agent_name as action_agent_name,
    pup14.brokerage_code as action_agent_brokerage_code,
    pup14.agent_email as action_agent_email,
    pup14.internal_verification_status as action_agent_verification_status,
    hla14.hlaagregateid as action_agent__hla,
    case when hla14.hlaagregateid is null then 'False' else 'True' end as action_agent_affiliated,
    sres.source as routing_source,
    case when sres.source = 'AUTO' then 'Auto-Routed' else null end as auto_route_flag
from routing_cte rc
left join profiles_cte pup1 on pup1.aggregate_id = rc.hla_selected_agent1
left join profiles_cte pup2 on pup2.aggregate_id = rc.hla_selected_agent2
left join profiles_cte pup3 on pup3.aggregate_id = rc.hla_selected_agent3
left join profiles_cte pup4 on pup4.aggregate_id = rc.agent1
left join profiles_cte pup5 on pup5.aggregate_id = rc.agent2
left join profiles_cte pup6 on pup6.aggregate_id = rc.agent3
left join profiles_cte pup7 on pup7.aggregate_id = rc.agent4
left join profiles_cte pup8 on pup8.aggregate_id = rc.agent5
left join profiles_cte pup9 on pup9.aggregate_id = rc.agent6
left join profiles_cte pup10 on pup10.aggregate_id = rc.agent7
left join profiles_cte pup11 on pup11.aggregate_id = rc.agent8
left join profiles_cte pup12 on pup12.aggregate_id = rc.agent9
left join profiles_cte pup13 on pup13.aggregate_id = rc.agent10
left join profiles_cte pup14 on pup14.aggregate_id = rc.action_agent
left join {{ ref('agent_hla_hierarchy') }} hla1 on hla1.agentaggregateid = rc.hla_selected_agent1
left join {{ ref('agent_hla_hierarchy') }} hla2 on hla2.agentaggregateid = rc.hla_selected_agent2
left join {{ ref('agent_hla_hierarchy') }} hla3 on hla3.agentaggregateid = rc.hla_selected_agent3
left join {{ ref('agent_hla_hierarchy') }} hla4 on hla4.agentaggregateid = rc.agent1
left join {{ ref('agent_hla_hierarchy') }} hla5 on hla5.agentaggregateid = rc.agent2 
left join {{ ref('agent_hla_hierarchy') }} hla6 on hla6.agentaggregateid = rc.agent3
left join {{ ref('agent_hla_hierarchy') }} hla7 on hla7.agentaggregateid = rc.agent4
left join {{ ref('agent_hla_hierarchy') }} hla8 on hla8.agentaggregateid = rc.agent5 
left join {{ ref('agent_hla_hierarchy') }} hla9 on hla9.agentaggregateid = rc.agent6 
left join {{ ref('agent_hla_hierarchy') }} hla10 on hla10.agentaggregateid = rc.agent7 
left join {{ ref('agent_hla_hierarchy') }} hla11 on hla11.agentaggregateid = rc.agent8
left join {{ ref('agent_hla_hierarchy') }} hla12 on hla12.agentaggregateid = rc.agent9
left join {{ ref('agent_hla_hierarchy') }} hla13 on hla13.agentaggregateid = rc.agent10 
left join {{ ref('agent_hla_hierarchy') }} hla14 on hla14.agentaggregateid = rc.action_agent
left join {{ ref('stg_leads_data_routing_events') }} ld on ld.lead_id = rc.lead_id
left join {{ ref('stg_routing_events_source') }} sres on sres.lead_id = rc.lead_id 