{{
  config(
    materialized = 'table',
    )
}}

with 
profiles_cte AS (
    select
    pup.aggregate_id,
    concat(pup.first_name,' ',pup.last_name) as agent_name,
    pup.brokerage_code,
    pup.email as agent_email
    from {{ ref("partner_user_profiles") }} pup
),
hs_enrollments as (
    select
	accept_time_delay_hrs,
	accept_to_contact_delay,
	actively_searching_status_time,
	agent_aggregate_id,
	agent_assign_time,
	agent_assign_time_unadjusted,
	agent_assigned,
	agent_email,
	agent_name,
	agent_phone,
	agent_status,
	agent_status_time,
	agentassign_time_delay_hrs,
	agentfirstname,
	agentlastname,
	agtcommpct,
	attached,
	attachment,
	attachment_code,
	attachment_reason,
	avg_price,
	bank_id,
	bank_name,
	bankcustomer,
	branchemployee,
	branchname,
	brokerage_code,
	brokerageroutingmethod,
	businesshours,
	category,
	citizenssalesforceenrollment,
	city,
	client_contact_approval,
	client_first_name,
	client_last_name,
	client_name,
	closeaddress,
	closedate,
	comments,
	consumer_confirmed,
	contactmethod,
	coverage,
	created,
	cst,
	cstdate,
	csthour,
	current_location,
	customereci,
	date,
	date_marked_closed_final,
	date_part,
	dow,
	escalatedtoconcierge,
	failc,
	faild,
	financeclosedate,
	first_agent_contact_time,
	first_contact_delay_from_enrollment,
	first_contact_time,
	first_time_wh,
	full_name,
	hb_status,
	hb_status_time,
	homesaleprice,
	id,
	inactivedate,
	inactiverole,
	last_agent_update,
	last_rc_update,
	lastpendingdate,
	lenderclosedwith,
	level_1_manager,
	level_1_manager_email,
	level_3_manager_email,
	level_3_manager_name,
	level_3_manager_region,
	level_4_manager_region,
	lo_aggregate_id,
	lo_email,
	lo_first_name,
	lo_last_name,
	lo_name,
	lo_nmlsid,
	lo_phone,
	lsuclosedate,
	major_status,
	mlo_assign_time,
	mlo_status,
	mlo_status_time,
	mlosubmission,
	mnth_yr,
	networkid,
	nmlsid,
	normalizedclosedate,
	outofnetwork,
	outofnetworkbrokerage,
	pending,
	pending_status_time,
	pendingclosedate,
	pendingpropertyaddress,
	ph_bank_name,
	ph_dd_division,
	ph_dd_email,
	ph_dd_name,
	ph_lm_email,
	ph_lm_name,
	ph_lo_email,
	ph_slm_manager,
	ph_slm_name,
	prequal,
	price_range_lower_bound,
	price_range_upper_bound,
	propertyaddress,
	propertyprice,
	purchase_location,
	purchase_time_frame,
	rc_accept_time_unadjusted,
	rc_city,
	rc_contact_first,
	rc_contact_last,
	rc_email,
	rc_mobile_phone,
	rc_name,
	rc_office_phone,
	rc_phone,
	rc_state,
	rc_status,
	rc_status_time,
	reporting_enroll_date,
	reporting_invite_date,
	sell_location,
	selling_address,
	source,
	state,
	system_enroll_date,
	system_invite_date,
	timetoinactive,
	traffic_campaign,
	traffic_medium,
	transaction_type,
	type_of_load_wh,
	updated_at,
	updated_in_wh,
	velocifyid,
	weeknum,
	year,
	zip
from {{ ref("leads_data_v3") }} ldv
)
,
{#- 
cte AS (
    SELECT
        LEAD_ID,
        agent_ids
    FROM {{ ref('stg_routing_events') }}
    where agent_ids is not null

)
,
 -#}

routing_cte AS (
select
	a.lead_id,
--ca.profile_aggregate_id,
a.smName,
a.event_type,
a.action_agent,
a.routing_method,
a.invite_token,
a.timestamp,
a.routing_start_time,
a.routing_initiated_time,
a.agent_limit,
a.parent_profile_id,
--lrp.not_parent_profile_id,
a.parent_division,
cast(a.hla_selected_agent1 as {{ uuid_formatter() }}) as hla_selected_agent1,
cast(a.hla_selected_agent2 as {{ uuid_formatter() }}) as hla_selected_agent2,
cast(a.hla_selected_agent3 as {{ uuid_formatter() }}) as hla_selected_agent3,
case when a.hla_selected_agent1 is not null then 'True' else 'False' end as advanced_agent_select_flag,
a.hla_selected_agent_count,
--lrp.data_field,
a.agent_count,
a.agent1,
a.agent2,
a.agent3,
a.agent4,
a.agent5,
a.agent6,
a.agent7,
a.agent8,
a.agent9,
a.agent10,
he.*
from {{ ref('stg_routing_events_hs') }} a
--left join lead_rank_params_cte lrp on lrp.lead_id = a.lead_id
--left join currently_assigned_agent_cte ca on ca.lead_id = a.lead_id
--left join profiles_cte pc on pc.aggregate_id = cast(_airbyte_data->'agents'->0->>'aggregateId' as uuid)
--left outer join profiles_cte pcc on pcc.aggregate_id = ca.profile_aggregate_id
left join hs_enrollments he on he.id = a.lead_id
)
select 
    rc.*,
    coalesce(pup1.agent_name,ld.ld_hla_selected_agent1_name) as hla_selected_agent1_name,
    coalesce(pup1.brokerage_code,ld.ld_hla_selected_agent1_brokerage_code) as hla_selected_agent1_brokerage_code,
    coalesce(pup1.agent_email,ld.ld_hla_selected_agent1_email) as hla_selected_agent1_email,
    coalesce(pup2.agent_name,ld.ld_hla_selected_agent2_name) as hla_selected_agent2_name,
    coalesce(pup2.brokerage_code,ld.ld_hla_selected_agent2_brokerage_code) as hla_selected_agent2_brokerage_code,
    coalesce(pup2.agent_email,ld.ld_hla_selected_agent2_email) as hla_selected_agent2_email,
    coalesce(pup3.agent_name,ld.ld_hla_selected_agent3_name) as hla_selected_agent3_name,
    coalesce(pup3.brokerage_code,ld.ld_hla_selected_agent3_brokerage_code) as hla_selected_agent3_brokerage_code,
    coalesce(pup3.agent_email,ld.ld_hla_selected_agent3_email) as hla_selected_agent3_email,
    pup4.agent_name as agent1_name,
    pup4.brokerage_code as agent1_brokerage_code,
    pup4.agent_email as agent1_email,
    pup5.agent_name as agent2_name,
    pup5.brokerage_code as agent2_brokerage_code,
    pup5.agent_email as agent2_email,
    pup6.agent_name as agent3_name,
    pup6.brokerage_code as agent3_brokerage_code,
    pup6.agent_email as agent3_email,
    pup7.agent_name as agent4_name,
    pup7.brokerage_code as agent4_brokerage_code,
    pup7.agent_email as agent4_email,
    pup8.agent_name as agent5_name,
    pup8.brokerage_code as agent5_brokerage_code,
    pup8.agent_email as agent5_email,
    pup9.agent_name as agent6_name,
    pup9.brokerage_code as agent6_brokerage_code,
    pup9.agent_email as agent6_email,
    pup10.agent_name as agent7_name,
    pup10.brokerage_code as agent7_brokerage_code,
    pup10.agent_email as agent7_email,
    pup11.agent_name as agent8_name,
    pup11.brokerage_code as agent8_brokerage_code,
    pup11.agent_email as agent8_email,
    pup12.agent_name as agent9_name,
    pup12.brokerage_code as agent9_brokerage_code,
    pup12.agent_email as agent9_email,
    pup13.agent_name as agent10_name,
    pup13.brokerage_code as agent10_brokerage_code,
    pup13.agent_email as agent10_email,
    pup14.agent_name as action_agent_name,
    pup14.brokerage_code as action_agent_brokerage_code,
    pup14.agent_email as action_agent_email
from routing_cte rc
left join profiles_cte pup1 on pup1.aggregate_id = rc.hla_selected_agent1
left join profiles_cte pup2 on pup2.aggregate_id = rc.hla_selected_agent2
left join profiles_cte pup3 on pup3.aggregate_id = rc.hla_selected_agent3
left join profiles_cte pup4 on pup4.aggregate_id = rc.agent1
left join profiles_cte pup5 on pup5.aggregate_id = rc.agent2
left join profiles_cte pup6 on pup6.aggregate_id = rc.agent3
left join profiles_cte pup7 on pup7.aggregate_id = rc.agent4
left join profiles_cte pup8 on pup8.aggregate_id = rc.agent5
left join profiles_cte pup9 on pup9.aggregate_id = rc.agent6
left join profiles_cte pup10 on pup10.aggregate_id = rc.agent7
left join profiles_cte pup11 on pup11.aggregate_id = rc.agent8
left join profiles_cte pup12 on pup12.aggregate_id = rc.agent9
left join profiles_cte pup13 on pup13.aggregate_id = rc.agent10
left join profiles_cte pup14 on pup14.aggregate_id = rc.action_agent
left join {{ ref('stg_leads_data_routing_events_hs') }} ld on ld.lead_id = rc.lead_id