with leads_cte AS (
    select 
        ld.*,
        pd.leadID,
        pd.activity_count,
        pd.activity_date,
        pd.activity_type,
        pd.inviting_nmlsid,
        replace(pd.inviting_lo,'  ',' ') as inviting_lo,
        pd.lo_contact_attempted,
        pd.partner,
        pd.declined,
        pd.decline_reason,
        pd.invitee_name,
        pd.total_opens,
        pd.total_clicks,
        pd.email_sent,
        pd.unique_campaign_open,
        pd.unique_campaign_click,
        pd.invite_id,
        pd.invite_email,
        pd.lofirstname,
        pd.lolastname,
        pd.agent,
        pd.purchase_specialist,
        pd.mlo_submission,
        pd.sms_invite_permission,
        pd.role,
        pd.loemail,
        pd.lastname,
        pd.firstname,
        pd.sendgrid,
        pd.shorthash,
        pd.utmsource,
        pd.disclosure,
        pd.phonenumber,
        pd.utmcampaign,
        pd.lophonenumber,
        pd.customerconnect,
        pd.confirmationrequired
         from {{ ref('leads_data_v3') }} ld 
    left outer join {{ ref('sofi_lo_invitations_warm_transfers') }} pd on ld.id = pd.leadId
    where ld.bank_name = 'SoFi'
)
,
invites_cte AS (
    select * from {{ ref('sofi_lo_invitations_warm_transfers') }}
    where leadid is null
)
select 
    lc.activity_count,
    lc.activity_date,
    case when lc.activity_type is null then 'Self-Enrolled' else lc.activity_type end as activity_type,
    lc.id as leadId,
    lc.inviting_nmlsid,lc.inviting_lo,lc.lo_contact_attempted,
    lc.declined, 
    'TRUE' as enrolled,
    replace(coalesce(lc.lo_name,lc.inviting_lo),'  ',' ') as lo_name_clean,
    coalesce(lc.lo_email,lc.loemail) as lo_email_clean,
    lc.decline_Reason, 
    lc.invitee_name,
    lc.date as enrolled_date,
    lc.nmlsid as enrollment_lo, lc.lo_name as enrollment_lo_name, lc.lo_phone as enrollment_lo_phone, lc.lo_email as enrollment_lo_email,
    lc.client_name, lc.client_email, lc.client_phone, lc.agent_name, lc.agent_email, lc.agent_phone,
    lc.purchase_location, lc.purchase_time_frame, lc.prequal, lc.price_range_lower_bound, lc.price_range_upper_bound, lc.bank_name,
    lc.total_opens, lc.total_clicks, lc.email_sent, lc.unique_campaign_open,
    lc.unique_campaign_click,
    lc.invite_id, lc.invite_email, lc.lofirstname, lc.lolastname,
    lc.agent, lc.purchase_specialist, lc.mlo_submission, lc.sms_invite_permission,
    lc.role, lc.loemail, lc.lastname, lc.firstname, lc.sendgrid,
    lc.shorthash, lc.utmsource, lc.disclosure, lc.phonenumber,
    lc.utmcampaign, lc.lophonenumber, lc.customerconnect, lc.confirmationrequired,
    coalesce(lc.closedate,lc.lsuclosedate) as closedate,
    lc.hb_status as hb_status,
    lc.hb_status_time as hb_status_time,
    lc.major_status,
    lc.last_agent_update,
    lc.transaction_type,
    ph.lm_name as ph_lm_name,
    ph.lm_email as ph_lm_email,
    ph.slm_name as ph_slm_name,
    ph.slm_manager as ph_slm_manager,
    ph.dd_name as ph_dd_name,
    ph.dd_email as ph_dd_email,
    ph.division as ph_division,
    p.lm_name as enrollment_lm,
    p.lm_email as enrollment_lm_email,
    p.slm_name as enrollment_slm_name,
    p.slm_manager as enrollment_slm_manager,
    p.dd_name as enrollment_dd_name,
    p.dd_email as enrollment_dd_email,
    p.division as enrollment_division
from leads_cte lc
left outer join {{ source('public', 'raw_partner_hierarchy') }} ph on ph.lo_email = lc.loemail
left outer join {{ source('public', 'raw_partner_hierarchy') }} p on p.lo_email = lc.lo_email OR p.lo_nmlsid = lc.nmlsid
UNION
select 
    ic.activity_count,
    ic.activity_date,
    case when ic.activity_type is null then 'Self-Enrolled' else ic.activity_type end as activity_type,
    ic.leadid as leadId,
    ic.inviting_nmlsid,ic.inviting_lo, 'NA' as lo_contact_attempted,
         'NA' as declined, 
         'False' as enrolled,
         replace(coalesce(inviting_lo,enrollment_lo_name),'  ',' ') as lo_name_clean,
        ic.loemail as lo_email_clean,
        'NA' as declineReason,ic.invitee_name,
        null as enrolled_date,
        '' as enrollment_lo, '' as enrollment_lo_name, '' as enrollment_lo_phone, '' as enrollment_lo_email,
        ic.client_name, ic.client_email, ic.client_phone, ic.agent_name, ic.agent_email, ic.agent_phone,
       ic.purchase_location, ic.purchase_time_frame, ic.prequal, ic.price_range_lower_bound, ic.price_range_upper_bound, ic.bank_name,
        ic.total_opens, ic.total_clicks, ic.email_sent, ic.unique_campaign_open,
        ic.unique_campaign_click,
        ic.invite_id, ic.invite_email, ic.lofirstname, ic.lolastname,
        ic.agent, ic.purchase_specialist, ic.mlo_submission, ic.sms_invite_permission,
        ic.role, ic.loemail, ic.lastname, ic.firstname, ic.sendgrid,
        ic.shorthash, ic.utmsource, ic.disclosure, ic.phonenumber,
        ic.utmcampaign, ic.lophonenumber, ic.customerconnect, ic.confirmationrequired,
        coalesce(ic.closedate,ic.lsuclosedate) as closedate,
        ic.hb_status as hb_status,
        ic.hb_status_time as hb_status_time,
        '' as major_status,
        ic.last_agent_update,
        ic.transaction_type,
        ph.lm_name as ph_lm_name,
        ph.lm_email as ph_lm_email,
        ph.slm_name as ph_slm_name,
        ph.slm_manager as ph_slm_manager,
        ph.dd_name as ph_dd_name,
        ph.dd_email as ph_dd_email,
        ph.division as ph_division,
        '' as enrollment_lm,
        '' as enrollment_lm_email,
        '' as enrollment_slm_name,
        '' as enrollment_slm_manager,
        '' as enrollment_dd_name,
        '' as enrollment_dd_email,
        '' as enrollment_division
    from invites_cte ic 
    left outer join {{ source('public', 'raw_partner_hierarchy') }} ph on ph.lo_email = ic.loemail